export const mockAgents = [
  {
    id: "agt_001",
    name: "Leave Policy Answer Bot",
    description: "This is a description of the leave policy answer bot which exceeds one line.",
    image: "/new-agent.jpg",
    tools: ["Gmail", "Git"],
    published: true,
    error: true,
  },
  {
    id: "agt_002",
    name: "Support Pro",
    description: "A customer support agent that answers FAQs and escalates complex issues.",
    image: "/support-agent.jpg",
    tools: ["Docs", "CRM", "Email"],
    published: true,
    error: false,
  },
  {
    id: "agt_003",
    name: "Research Analyst",
    description: "Scans the web, summarizes findings, and provides citations.",
    image: "/research-agent.jpg",
    tools: ["Web", "Notes", "Citations"],
    published: false,
    error: false,
  },
  {
    id: "agt_004",
    name: "Meeting Summarizer",
    description: "Joins calls, records, and drafts summary notes with action items.",
    image: "/meeting-agent.jpg",
    tools: ["Calendar", "Transcribe", "Docs"],
    published: true,
    error: true,
  },
  {
    id: "agt_005",
    name: "Marketing Copywriter",
    description: "Creates high-converting landing page copy and A/B test variants.",
    image: "/marketing-agent.jpg",
    tools: ["SEO", "A/B", "Analytics", "CMS"],
    published: false,
    error: false,
  },
  {
    id: "agt_006",
    name: "Code Review Assistant",
    description: "Analyzes pull requests and suggests improvements for code quality.",
    image: "/code-agent.jpg",
    tools: ["GitHub", "Git", "Slack"],
    published: true,
    error: false,
  },
  {
    id: "agt_007",
    name: "Invoice Manager",
    description: "Processes invoices, tracks payments, and sends reminders automatically.",
    image: "/invoice-agent.jpg",
    tools: ["QuickBooks", "Gmail", "Sheets"],
    published: false,
    error: false,
  },
  {
    id: "agt_008",
    name: "Social Media Scheduler",
    description: "Plans and publishes content across multiple social platforms.",
    image: "/social-agent.jpg",
    tools: ["Twitter", "LinkedIn", "Instagram", "Facebook"],
    published: true,
    error: false,
  },
  {
    id: "agt_009",
    name: "Data Analytics Bot",
    description: "Generates reports and visualizations from your business data.",
    image: "/analytics-agent.jpg",
    tools: ["BigQuery", "Tableau", "Sheets"],
    published: false,
    error: true,
  },
  {
    id: "agt_010",
    name: "Onboarding Coordinator",
    description: "Guides new employees through setup, paperwork, and training.",
    image: "/onboarding-agent.jpg",
    tools: ["HR Portal", "Docs", "Calendar", "Slack"],
    published: true,
    error: false,
  },
  {
    id: "agt_011",
    name: "Bug Tracker",
    description: "Monitors error logs and automatically creates tickets with context.",
    image: "/bug-agent.jpg",
    tools: ["Jira", "Sentry", "GitHub"],
    published: false,
    error: false,
  },
  {
    id: "agt_012",
    name: "Content Moderator",
    description: "Reviews user submissions and flags inappropriate content.",
    image: "/moderator-agent.jpg",
    tools: ["AI Vision", "Database", "Slack"],
    published: true,
    error: false,
  },
  {
    id: "agt_013",
    name: "Sales Lead Qualifier",
    description: "Scores and prioritizes incoming leads based on fit and intent.",
    image: "/sales-agent.jpg",
    tools: ["CRM", "Gmail", "LinkedIn"],
    published: false,
    error: false,
  },
  {
    id: "agt_014",
    name: "Inventory Tracker",
    description: "Monitors stock levels and triggers reorder alerts when low.",
    image: "/inventory-agent.jpg",
    tools: ["ERP", "Sheets", "Gmail"],
    published: true,
    error: true,
  },
  {
    id: "agt_015",
    name: "Newsletter Generator",
    description: "Curates content and designs weekly newsletters for subscribers.",
    image: "/newsletter-agent.jpg",
    tools: ["Mailchimp", "RSS", "Canva"],
    published: false,
    error: false,
  },
]
